"""initial database schema

Revision ID: 1698088aefd3
Revises: 
Create Date: 2026-08-12 22:15:50.139262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1698088aefd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lorries',
    sa.Column('lorry_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('lorry_id')
    )
    op.create_index(op.f('ix_lorries_registration_number'), 'lorries', ['registration_number'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('expense_categories',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loading_date', sa.Date(), nullable=False),
    sa.Column('lorry_id', sa.BigInteger(), nullable=False),
    sa.Column('loading_location', sa.String(length=150), nullable=False),
    sa.Column('unloading_location', sa.String(length=150), nullable=False),
    sa.Column('freight_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lorry_id'], ['lorries.lorry_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index(op.f('ix_trips_loading_date'), 'trips', ['loading_date'], unique=False)
    op.create_index(op.f('ix_trips_lorry_id'), 'trips', ['lorry_id'], unique=False)
    op.create_table('monthly_expenses',
    sa.Column('monthly_expense_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('lorry_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.category_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lorry_id'], ['lorries.lorry_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('monthly_expense_id')
    )
    op.create_index(op.f('ix_monthly_expenses_category_id'), 'monthly_expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_monthly_expenses_expense_date'), 'monthly_expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_monthly_expenses_lorry_id'), 'monthly_expenses', ['lorry_id'], unique=False)
    op.create_table('trip_expenses',
    sa.Column('trip_expense_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.category_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_expense_id')
    )
    op.create_index(op.f('ix_trip_expenses_category_id'), 'trip_expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_trip_expenses_trip_id'), 'trip_expenses', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_expenses_trip_id'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_category_id'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    op.drop_index(op.f('ix_monthly_expenses_lorry_id'), table_name='monthly_expenses')
    op.drop_index(op.f('ix_monthly_expenses_expense_date'), table_name='monthly_expenses')
    op.drop_index(op.f('ix_monthly_expenses_category_id'), table_name='monthly_expenses')
    op.drop_table('monthly_expenses')
    op.drop_index(op.f('ix_trips_lorry_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_loading_date'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lorries_registration_number'), table_name='lorries')
    op.drop_table('lorries')
    # ### end Alembic commands ###
